### ISSUE TITLE
Dumb Question

### ISSUE THREAD

**Issue by iGetUploaded** [Naru-kami/BackgroundManager-plugin#2]
How is it used?

**Comment by Naru-kami** [comment]
An icon will be added to the toolbar, which opens a popup.
Inside, there's an input field, where you can
- paste an image,
- drag and drop an image, or
- open the file explorer and select an image from your computer.
It will be added to the list of background images.

From the little cog icon, you can enable and adjust
- the slideshow feature
- transition when swapping background images
and some other minor things.

To restore the original background image of the theme you are using, click the "Remove Custom Background" right under the cog.

To set a background image, simply click the image for it. Or to delete it, click "Delete Image" on the upper right corner of the same image.

It is intended to use in conjunction with themes, that have a background image. To get the full experience, you need to set one.
It is mainly used for the slideshow feature, to shuffle a set of background images.

**Comment by iGetUploaded** [comment]
Ah okay thank you
