### ISSUE TITLE
[Bug] Wallpapers Seem to unload after a while

### ISSUE THREAD

**Issue by Riddim-GLiTCH** [Naru-kami/BackgroundManager-plugin#3]
I have observed that the plugin seems to unload all backgrounds after a while of having the discord app open. I remedied this by restarting the client. I am not sure what may have caused this, but I figured I should let you know. As this a mildly annoying bug.

What I have observed is that the plugin seems to unload the selected background image after a few hours on my particular machine. After this, It seems to stop injecting into the CSS entirely, Even after deselecting and re-selecting the image. Instead falling back to the original wallpaper image of the theme.

What I suspect might be happening is that discord occasionally does some housekeeping and unloads some cached data, which is where I am guessing the backgrounds are stored from the light reading I have done on the plugins code earlier. (this is of course light reading of a language I do not know, so I could be terribly wrong, I am sorry if I am.)

Potentially important information that I am able to provide:
Discord Version: `canary 350930 (08950ef)` 
Host: `1.0.894 x64 (56216)` 
OS: `Windows 11 64-bit (10.0.26100)`
BetterDiscord Version: `1.10.2 (Theme Developer Test)` [Provided by Zerebos [Here](https://canary.discord.com/channels/947985618502307840/948648369516060722/1313975835257999450). (This links requires access to the BetterDiscord Developer Community Server.)

Sidenote: While writing this post, I observed this behavior happening again after minimizing the client. This seems to be a reliable way of recreating this behavior, Hope this helps debug the issue with the lack of information that I am able to produce. Apologies for that.

**Comment by Naru-kami** [comment]
Sorry for the late response. So, if I understand this correctly, this bug prevents you from selecting any background from the popout completely? And the current background will _unload_, defaulting to the original wallpaper? I have a few guesses as to what might be the cause, but to narrow it down, I would need to know:
- Does restarting the plugin also remedy it, or do you need the full client restart? If yes, the injected containers holding the background might've been removed. You can actually check this if you querySelect 'BackgroundManager-bgContainer'
- Did you enable "overwrite CSS" in the settings?
- Did you enable slideshow mode (with more or less than 2 images; with or without shuffle)? You mentioned minimizing the client. I do check if the client is visible to avoid unnecessary renders. The objectURL might've been revoked here, though I highly doubt it.
- Do you use more than 1 theme?

I haven't encountered this bug on the stable version, but I have yet to test it on the other versions.

**Comment by Riddim-GLiTCH** [comment]
> Does restarting the plugin also remedy it, or do you need the full client restart? If yes, the injected containers holding the background might've been removed. You can actually check this if you querySelect 'BackgroundManager-bgContainer'
It does. And the selector you mention does not exist.

> Did you enable "overwrite CSS" in the settings?
I have it enabled.

> Did you enable slideshow mode (with more or less than 2 images; with or without shuffle)? You mentioned minimizing the client. I do check if the client is visible to avoid unnecessary renders. The objectURL might've been revoked here, though I highly doubt it.
No, I only use a single wallpaper.

>Do you use more than 1 theme?
I only use a single theme, however, this theme is one of those themes that I have put together over the course of a few months by collecting snippets all over and addincg a couple of my own.

**Comment by Naru-kami** [comment]
If you cannot find that class, then discord is clearly removing that container. I'll have to patch the react component then instead of simple dom manipulation. Thank you for notifying.
