### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by PmikeGamer** [Naru-kami/BackgroundManager-plugin#4]
it crashes discord as soon as you apply a background
tried with basicbackground and it crashed

**Comment by Naru-kami** [comment]
Seems like the discord update broke a few things. I'll try to fix it asap.

**Comment by Naru-kami** [comment]
Are you still experiencing the issue with the new version? If yes, I'd need a bit more information on this. If not, I'll close this.

**Comment by PmikeGamer** [comment]
It is fixed now, thank you
